server:
  port: ${PORT:8862}
#eureka:
#  client:
#    register-with-eureka: false
#    serviceurl: defaultZone=http://localhost:8850
eureka:
  client:
    register-with-eureka: true
    #fetch-registry: false
    serviceurl:
      defaultZone: http://localhost:8850/eureka/
message: Configuracion customer en el servidor levantado!
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 12345678
    url: jdbc:mysql://localhost:3306/crudcloud?serverTimezone=UTC
    username: root
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQLDialect
  cloud:
    config:
      uri: http://localhost.8860
